title: Publication List 
description: Fumitaka Hoshino
theme: jekyll-theme-modernist
lsi: false
safe: true
source: fhoshino52/fhoshino52.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
