title: Publication List (Fumitaka Hoshino)
author: Fumitaka Hoshino
theme: jekyll-theme-tactile
lsi: false
safe: true
source: fhoshino52/fhoshino52.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
